## 桁修正 年金

##単位変換 金額：10億円　人口：千人　%：百分率
base$P_REV_OTH_WORK = base$P_REV_OTH_WORK*10^3
base$P_REV_OTH_KOKU = base$P_REV_OTH_KOKU*10^3

base$P_EXP_OTH_WORK = base$P_EXP_OTH_WORK*10^3
base$P_EXP_OTH_KOKU = base$P_EXP_OTH_KOKU*10^3

base$P_EXP_KOKU = base$P_EXP_KOKU/10^6
base$P_GRA_KOKU = base$P_GRA_KOKU/10^6

base$P_EXP_KISO = base$P_EXP_KISO/10^6

base$P_EXP_KOSEI = base$P_EXP_KOSEI/10^6
base$P_GRA_KOSEI = base$P_GRA_KOSEI/10^6
base$P_EXP_KOKKA = base$P_EXP_KOKKA/10^6
base$P_GRA_KOKKA = base$P_GRA_KOKKA/10^6

base$P_EXP_CHIHOU_TAISHOKU = base$P_EXP_CHIHOU_TAISHOKU/10^6
base$P_EXP_CHIHOU_SHOGAI = base$P_EXP_CHIHOU_SHOGAI/10^6
base$P_EXP_CHIHOU_IZOKU = base$P_EXP_CHIHOU_IZOKU/10^6
base$P_GRA_CHIHOU = base$P_GRA_CHIHOU/10^6

base$P_EXP_SHIGAKU_TAISHOKU = base$P_EXP_SHIGAKU_TAISHOKU/10^6
base$P_EXP_SHIGAKU_SHOGAI = base$P_EXP_SHIGAKU_SHOGAI/10^6
base$P_EXP_SHIGAKU_IZOKU = base$P_EXP_SHIGAKU_IZOKU/10^6
base$P_GRA_SHIGAKU = base$P_GRA_SHIGAKU/10^6

base$P_REV_KOKU = base$P_REV_KOKU/10^6 
base$P_REV_KOKKA = base$P_REV_KOKKA/10^6 
base$P_REV_CHIHOU = base$P_REV_CHIHOU/10^6 
base$P_REV_SHIGAKU = base$P_REV_SHIGAKU/10^6 
base$P_REV_KOSEI = base$P_REV_KOSEI/10^6 


base$P_RESERVE_KOKU = base$P_RESERVE_KOKU*10^3
base$P_RESERVE_WORK = base$P_RESERVE_WORK*10^3


base$P_REV_KOKKA_KAKE = base$P_REV_KOKKA_KAKE/10^6
base$P_REV_CHIHOU_KAKE = base$P_REV_CHIHOU_KAKE/10^6

base$P_REWARD = base$P_REWARD*10^3


base$P_RPRE_KOSEI = base$P_RPRE_KOSEI/100

base$P_RNOHU = base$P_RNOHU/100

base$P_NPOP_JUKYU_KISO = base$P_NPOP_JUKYU_KISO/10^3


base$P_NPOP_JUKYU_KOSEI = base$P_NPOP_JUKYU_KOSEI/10^3
base$P_NPOP_JUKYU_KOKKA = base$P_NPOP_JUKYU_KOKKA/10^3
base$P_NPOP_JUKYU_CHIHOU = base$P_NPOP_JUKYU_CHIHOU/10^3
base$P_NPOP_JUKYU_SHIGAKU = base$P_NPOP_JUKYU_SHIGAKU/10^3


base$P_NPOP_ICHI = base$P_NPOP_ICHI/10^3
base$P_NPOP_ICHI_SANTEI = base$P_NPOP_ICHI_SANTEI*10^3

base$P_NPOP_NI_KOSEI = base$P_NPOP_NI_KOSEI/10^3
base$P_NPOP_NI_KOKKA = base$P_NPOP_NI_KOKKA/10^3
base$P_NPOP_NI_CHIHOU = base$P_NPOP_NI_CHIHOU/10^3
base$P_NPOP_NI_SHIGAKU = base$P_NPOP_NI_SHIGAKU/10^3

base$P_NPOP_SAN_KOSEI = base$P_NPOP_SAN_KOSEI/10^3
base$P_NPOP_SAN_KOKKA = base$P_NPOP_SAN_KOKKA/10^3
base$P_NPOP_SAN_CHIHOU = base$P_NPOP_SAN_CHIHOU/10^3
base$P_NPOP_SAN_SHIGAKU = base$P_NPOP_SAN_SHIGAKU/10^3

base$P_NPOP_SAN = base$P_NPOP_SAN/10^3

base$P_RMENJO = base$P_RMENJO/100
base$P_MPRE_KOKU = base$P_MPRE_KOKU/10^9


base$P_LIAB_KOKU = base$P_LIAB_KOKU/10^6
base$P_EXP_KOKU_KISO = base$P_EXP_KOKU_KISO/10
base$P_EXP_WORK_KISO = base$P_EXP_WORK_KISO/10^6

